## Метод прогонки


In [1]:
import numpy as np

Вариант 17

In [2]:
N = 5
A = np.zeros((N, N))
A[0, 0] = -6
A[0, 1] = 5
A[1, 0] = -1
A[1, 1] = 13
A[1, 2] = 6
A[2, 1] = -9
A[2, 2] = -15
A[2, 3] = -4
A[3, 2] = -1
A[3, 3] = -7
A[3, 4] = 1
A[4, 3] = 9
A[4, 4] = -18

d = np.array([51, 100, -12, 47, 90])

print("Матрица системы: \n", A)
print("правая часть: \n", d)

Матрица системы: 
 [[ -6.   5.   0.   0.   0.]
 [ -1.  13.   6.   0.   0.]
 [  0.  -9. -15.  -4.   0.]
 [  0.   0.  -1.  -7.   1.]
 [  0.   0.   0.   9. -18.]]
правая часть: 
 [ 51 100 -12  47  90]


In [3]:
def progonka(A, d):
    N = A.shape[0]
    A1 = A.copy()
    x = np.zeros(N)
    Q = np.zeros(N)
    P = np.zeros(N)
    P[0] = -(A1[0, 1])/(A1[0, 0]) #прямой ход: вычисляем прогоночные коэффициенты
    Q[0] = d[0] / A1[0, 0] #отдельно для первого и последнего уравнений, циклом для всех остальных
    for i in range(1, N-1):
        P[i] = - (A1[i, i+1]) / (A1[i, i] + A1[i, i-1] * P[i-1]) 
        Q[i] = (d[i] - A1[i, i-1] * Q[i-1]) / (A1[i, i] + A1[i, i-1] * P[i-1])
    P[-1] = 0
    Q[-1] = (d[-1] - A1[-1, -2] * Q[-2]) / (A1[-1, -1] + A1[-1, -2] * P[-2])
    #print("P: ", P)
    #print("Q: ", Q)
    
    x[N-1] = Q[N-1] #обратный ход, вычисляем переменные начиная с последнего уравнения (его считаем отдельно)
    for j in range(N-2, -1, -1): 
        x[j] = P[j] * x[j+1] + Q[j]
    return x

In [4]:
x = progonka(A, d)
print("x = ", x)

x =  [-1.25426422  8.69488293 -2.38129039 -7.63364763 -8.81682382]


In [12]:
np.testing.assert_allclose(A  @ x, d)

Пример для самопроверки (из методички, все иксы равны 1)

In [14]:
A = np.zeros((4,4))
A[0, 0] = 8
A[0, 1] = -2
A[1, 0] = -1
A[1, 1] = 6
A[1, 2] = -2
A[2, 1] = 2
A[2, 2] = 10
A[2, 3] = -4
A[3, 2] = -1
A[3, 3] = 6

d = np.array([6,3,8,5])

x = progonka(A, d)
x

array([1., 1., 1., 1.])